BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE HOTEL_FEATURE_JOIN';
    EXCEPTION
        WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE HOTEL';
    EXCEPTION
        WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE HOTEL_ACCOUNT';
    EXCEPTION
        WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE HOTEL_FEATURE';
    EXCEPTION
        WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SECTION';
    EXCEPTION
        WHEN OTHERS THEN NULL;
END;
/






-- 地區資料表
CREATE TABLE SECTION
(
    CODE VARCHAR2(5) NOT NULL,
    NAME VARCHAR2(20) NOT NULL,
    CONSTRAINT SECTION_PK PRIMARY KEY (CODE)
);

COMMENT ON COLUMN SECTION.CODE IS '地區編碼';
COMMENT ON COLUMN SECTION.NAME IS '地區名稱';

INSERT INTO SECTION (CODE, NAME) VALUES ('KLU', '基隆市');
INSERT INTO SECTION (CODE, NAME) VALUES ('TPH', '新北市');
INSERT INTO SECTION (CODE, NAME) VALUES ('TPE', '臺北市');
INSERT INTO SECTION (CODE, NAME) VALUES ('TYC', '桃園市');
INSERT INTO SECTION (CODE, NAME) VALUES ('HSH', '新竹縣');
INSERT INTO SECTION (CODE, NAME) VALUES ('HSC', '新竹市');
INSERT INTO SECTION (CODE, NAME) VALUES ('MAC', '苗栗市');
INSERT INTO SECTION (CODE, NAME) VALUES ('MAL', '苗栗縣');
INSERT INTO SECTION (CODE, NAME) VALUES ('TXG', '臺中市');
INSERT INTO SECTION (CODE, NAME) VALUES ('CWH', '彰化縣');
INSERT INTO SECTION (CODE, NAME) VALUES ('CWS', '彰化市');
INSERT INTO SECTION (CODE, NAME) VALUES ('NTC', '南投市');
INSERT INTO SECTION (CODE, NAME) VALUES ('NTO', '南投縣');
INSERT INTO SECTION (CODE, NAME) VALUES ('YLH', '雲林縣');
INSERT INTO SECTION (CODE, NAME) VALUES ('CHY', '嘉義縣');
INSERT INTO SECTION (CODE, NAME) VALUES ('CYI', '嘉義市');
INSERT INTO SECTION (CODE, NAME) VALUES ('TNN', '臺南市');
INSERT INTO SECTION (CODE, NAME) VALUES ('KHH', '高雄市');
INSERT INTO SECTION (CODE, NAME) VALUES ('IUH', '屏東縣');
INSERT INTO SECTION (CODE, NAME) VALUES ('PTS', '屏東市');
INSERT INTO SECTION (CODE, NAME) VALUES ('ILN', '宜蘭縣');
INSERT INTO SECTION (CODE, NAME) VALUES ('ILC', '宜蘭市');
INSERT INTO SECTION (CODE, NAME) VALUES ('HWA', '花蓮縣');
INSERT INTO SECTION (CODE, NAME) VALUES ('HWC', '花蓮市');
INSERT INTO SECTION (CODE, NAME) VALUES ('TTC', '臺東市');
INSERT INTO SECTION (CODE, NAME) VALUES ('TTT', '臺東縣');
INSERT INTO SECTION (CODE, NAME) VALUES ('PEH', '澎湖縣');
INSERT INTO SECTION (CODE, NAME) VALUES ('GNI', '綠島');
INSERT INTO SECTION (CODE, NAME) VALUES ('KYD', '蘭嶼');
INSERT INTO SECTION (CODE, NAME) VALUES ('KMN', '金門縣');
INSERT INTO SECTION (CODE, NAME) VALUES ('MZW', '馬祖');
INSERT INTO SECTION (CODE, NAME) VALUES ('LNN', '連江縣');


-- 飯店特色資料表
CREATE TABLE HOTEL_FEATURE
(
    ID NUMBER NOT NULL,
    TEXT VARCHAR2(30) NOT NULL,
    CONSTRAINT HOTEL_FEATURE_PK PRIMARY KEY (ID)
);

COMMENT ON COLUMN HOTEL_FEATURE.ID IS '飯店特色編號';
COMMENT ON COLUMN HOTEL_FEATURE.TEXT IS '飯店特色文字';

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE HOTEL_FEATURE_SEQ';
    EXCEPTION
        WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE HOTEL_FEATURE_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

INSERT INTO HOTEL_FEATURE (ID, TEXT) VALUES (HOTEL_FEATURE_SEQ.NEXTVAL, '房內免費Wi-Fi');
INSERT INTO HOTEL_FEATURE (ID, TEXT) VALUES (HOTEL_FEATURE_SEQ.NEXTVAL, '停車場');
INSERT INTO HOTEL_FEATURE (ID, TEXT) VALUES (HOTEL_FEATURE_SEQ.NEXTVAL, '可寄放行李');



-- 飯店帳號資料表
CREATE TABLE HOTEL_ACCOUNT
(
    ID NUMBER NOT NULL,
    ACCOUNT VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(50) NOT NULL,
    CONSTRAINT HOTEL_ACCOUNT_PK PRIMARY KEY (ID)
);

COMMENT ON COLUMN HOTEL_ACCOUNT.ID IS '飯店帳號編號';
COMMENT ON COLUMN HOTEL_ACCOUNT.ACCOUNT IS '飯店帳號';
COMMENT ON COLUMN HOTEL_ACCOUNT.PASSWORD IS '飯店密碼';

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE HOTEL_ACCOUNT_SEQ';
    EXCEPTION
        WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE HOTEL_ACCOUNT_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

INSERT INTO HOTEL_ACCOUNT (ID, ACCOUNT, PASSWORD) VALUES (HOTEL_ACCOUNT_SEQ.NEXTVAL, 'A123456', '111111');
INSERT INTO HOTEL_ACCOUNT (ID, ACCOUNT, PASSWORD) VALUES (HOTEL_ACCOUNT_SEQ.NEXTVAL, 'B123456', '222222');
INSERT INTO HOTEL_ACCOUNT (ID, ACCOUNT, PASSWORD) VALUES (HOTEL_ACCOUNT_SEQ.NEXTVAL, 'C123456', '333333');
INSERT INTO HOTEL_ACCOUNT (ID, ACCOUNT, PASSWORD) VALUES (HOTEL_ACCOUNT_SEQ.NEXTVAL, 'D123456', '444444');
INSERT INTO HOTEL_ACCOUNT (ID, ACCOUNT, PASSWORD) VALUES (HOTEL_ACCOUNT_SEQ.NEXTVAL, 'E123456', '555555');


-- 飯店資料表
CREATE TABLE HOTEL
(
    ID NUMBER NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    SECTION_CODE VARCHAR2(5) NOT NULL,
    ADDRESS VARCHAR2(150) NOT NULL,
    INTRODUCTION VARCHAR2(300),
    IMG_NAME VARCHAR2(50) NOT NULL,
    ACCOUNT_ID NUMBER NOT NULL,
    CONSTRAINT HOTEL_PK PRIMARY KEY (ID),
    CONSTRAINT HOTEL_TO_SECTION_FK FOREIGN KEY (SECTION_CODE) REFERENCES SECTION (CODE),
    CONSTRAINT HOTEL_TO_HOTEL_ACCOUNT_FK FOREIGN KEY (ACCOUNT_ID) REFERENCES HOTEL_ACCOUNT (ID)
);

COMMENT ON COLUMN HOTEL.ID IS '飯店編號';
COMMENT ON COLUMN HOTEL.NAME IS '飯店名稱';
COMMENT ON COLUMN HOTEL.SECTION_CODE IS '飯店區域';
COMMENT ON COLUMN HOTEL.ADDRESS IS '飯店地址';
COMMENT ON COLUMN HOTEL.INTRODUCTION IS '飯店介紹';
COMMENT ON COLUMN HOTEL.IMG_NAME IS '飯店照片名稱';
COMMENT ON COLUMN HOTEL.ACCOUNT_ID IS '飯店帳號編號';

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE HOTEL_SEQ';
    EXCEPTION
        WHEN OTHERS THEN NULL;
END;
/
CREATE SEQUENCE HOTEL_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

INSERT INTO HOTEL (ID, NAME, SECTION_CODE, ADDRESS, INTRODUCTION, IMG_NAME, ACCOUNT_ID) VALUES (HOTEL_SEQ.NEXTVAL, '忠義飯店', 'TPE', '台北市XX路XX號', '好飯店', 'img1.jpg', 1);
INSERT INTO HOTEL (ID, NAME, SECTION_CODE, ADDRESS, INTRODUCTION, IMG_NAME, ACCOUNT_ID) VALUES (HOTEL_SEQ.NEXTVAL, '中和飯店', 'TPH', '新北市YY路YYY號', '很好飯店', 'img2.jpg', 2);
INSERT INTO HOTEL (ID, NAME, SECTION_CODE, ADDRESS, INTRODUCTION, IMG_NAME, ACCOUNT_ID) VALUES (HOTEL_SEQ.NEXTVAL, '凱薩大酒店', 'HSC', '新竹市ZZZ路ZZ號', '棒飯店', 'img3.jpg', 3);
INSERT INTO HOTEL (ID, NAME, SECTION_CODE, ADDRESS, INTRODUCTION, IMG_NAME, ACCOUNT_ID) VALUES (HOTEL_SEQ.NEXTVAL, '揚名飯店', 'TNN', '台南市G路GGG號', '非常好飯店', 'img4.jpg', 4);
INSERT INTO HOTEL (ID, NAME, SECTION_CODE, ADDRESS, INTRODUCTION, IMG_NAME, ACCOUNT_ID) VALUES (HOTEL_SEQ.NEXTVAL, '吳麗飯店', 'TTC', '台東市UUU路UUUUU號', '極好飯店', 'img5.jpg', 5);


-- 飯店特色聯集資料表
CREATE TABLE HOTEL_FEATURE_JOIN
(
    HOTEL_ID NUMBER NOT NULL,
    FEATURE_ID NUMBER NOT NULL,
    CONSTRAINT HOTEL_FEATURE_JOIN_TO_HOTEL_FK FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL (ID),
    CONSTRAINT HOTEL_FEATURE_JOIN_TO_HOTEL_FEATURE_FK FOREIGN KEY (FEATURE_ID) REFERENCES HOTEL_FEATURE (ID)
);

COMMENT ON COLUMN HOTEL_FEATURE_JOIN.HOTEL_ID IS '飯店編號';
COMMENT ON COLUMN HOTEL_FEATURE_JOIN.FEATURE_ID IS '飯店特色名稱';


INSERT INTO HOTEL_FEATURE_JOIN (HOTEL_ID, FEATURE_ID) VALUES (1, 1);
INSERT INTO HOTEL_FEATURE_JOIN (HOTEL_ID, FEATURE_ID) VALUES (1, 2);
INSERT INTO HOTEL_FEATURE_JOIN (HOTEL_ID, FEATURE_ID) VALUES (2, 2);
INSERT INTO HOTEL_FEATURE_JOIN (HOTEL_ID, FEATURE_ID) VALUES (2, 3);
INSERT INTO HOTEL_FEATURE_JOIN (HOTEL_ID, FEATURE_ID) VALUES (3, 1);
INSERT INTO HOTEL_FEATURE_JOIN (HOTEL_ID, FEATURE_ID) VALUES (3, 2);
INSERT INTO HOTEL_FEATURE_JOIN (HOTEL_ID, FEATURE_ID) VALUES (3, 3);
INSERT INTO HOTEL_FEATURE_JOIN (HOTEL_ID, FEATURE_ID) VALUES (4, 1);
INSERT INTO HOTEL_FEATURE_JOIN (HOTEL_ID, FEATURE_ID) VALUES (4, 2);
INSERT INTO HOTEL_FEATURE_JOIN (HOTEL_ID, FEATURE_ID) VALUES (4, 3);
INSERT INTO HOTEL_FEATURE_JOIN (HOTEL_ID, FEATURE_ID) VALUES (5, 3);



COMMIT;