server:
  port: 8086
  servlet:
    context-path: /roomBooking
    
    
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: ROOM_BOOKING
    password: root
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 3000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        "[format_sql]": true
    